<a href="https://colab.research.google.com/github/Sudhaganisrinidhi/B_20_1342/blob/main/Lab3_Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Generate a 4x4 array of test scores (example: random integers 50–100)
scores = np.random.randint(50, 101, size=(4, 4))
print("Test Scores (4x4):\n", scores, "\n")

# Row-wise and column-wise means
row_means = np.mean(scores, axis=1)
col_means = np.mean(scores, axis=0)

print("Row-wise Means:", row_means)
print("Column-wise Means:", col_means, "\n")

# Standard deviation and variance
std_dev = np.std(scores)
variance = np.var(scores)
print("Standard Deviation (overall):", std_dev)
print("Variance (overall):", variance, "\n")

# Global min and max with indices
global_max = np.max(scores)
global_min = np.min(scores)
max_index = np.unravel_index(np.argmax(scores), scores.shape)
min_index = np.unravel_index(np.argmin(scores), scores.shape)

print("Global Max:", global_max, "at index", max_index)
print("Global Min:", global_min, "at index", min_index, "\n")

# Median
median = np.median(scores)
print("Median (overall):", median)

Test Scores (4x4):
 [[74 85 78 72]
 [89 87 75 73]
 [98 65 51 96]
 [69 78 91 81]] 

Row-wise Means: [77.25 81.   77.5  79.75]
Column-wise Means: [82.5  78.75 73.75 80.5 ] 

Standard Deviation (overall): 11.741353201398892
Variance (overall): 137.859375 

Global Max: 98 at index (np.int64(2), np.int64(0))
Global Min: 51 at index (np.int64(2), np.int64(2)) 

Median (overall): 78.0


In [2]:
import numpy as np

# Create a 3x3x3 RGB image (values 0–255)
image = np.random.randint(0, 256, (3, 3, 3), dtype=np.uint8)
print("Original RGB Image Array:\n", image, "\n")

# Extract color channels using slicing
red_channel   = image[:, :, 0]
green_channel = image[:, :, 1]
blue_channel  = image[:, :, 2]

print("Red Channel:\n", red_channel, "\n")
print("Green Channel:\n", green_channel, "\n")
print("Blue Channel:\n", blue_channel, "\n")

# Average intensity per channel
avg_red   = np.mean(red_channel)
avg_green = np.mean(green_channel)
avg_blue  = np.mean(blue_channel)

print("Average Intensities - R:", avg_red,
      "G:", avg_green,
      "B:", avg_blue, "\n")

# Brighten image by adding scalar (clip to 255)
bright_image = np.clip(image + 50, 0, 255)
print("Brightened Image Array:\n", bright_image, "\n")

Original RGB Image Array:
 [[[251 137  43]
  [105 219  30]
  [ 34  33 169]]

 [[198 125 176]
  [129 240 113]
  [241  20 174]]

 [[ 52 144  92]
  [131 119 120]
  [ 24 169 107]]] 

Red Channel:
 [[251 105  34]
 [198 129 241]
 [ 52 131  24]] 

Green Channel:
 [[137 219  33]
 [125 240  20]
 [144 119 169]] 

Blue Channel:
 [[ 43  30 169]
 [176 113 174]
 [ 92 120 107]] 

Average Intensities - R: 129.44444444444446 G: 134.0 B: 113.77777777777777 

Brightened Image Array:
 [[[ 45 187  93]
  [155  13  80]
  [ 84  83 219]]

 [[248 175 226]
  [179  34 163]
  [ 35  70 224]]

 [[102 194 142]
  [181 169 170]
  [ 74 219 157]]] 

