<a href="https://colab.research.google.com/github/Sudhaganisrinidhi/B_20_1342/blob/main/Lab3_Files_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# writing to a file
#open file in write mode
fp=open("example.txt","w")
#write text to file
fp.write("Hello, B.tech students|\n")
fp.write("This is file handling in python.\n")
fp.write("sr university")
fp.write("suresh kumar")
#close file
fp.close()
print("Data written successfully!")

Data written successfully!


In [3]:
#Reading fron a file
#open file in read mode
file=open("example.txt", "r")
#read entire content
content=file.read()
print(content)
#close file
file.close()

Hello, B.tech students|
This is file handling in python.
sr universitysuresh kumar


In [11]:
#reading line by line
file=open("example.txt","r")
line1=file.readline()
print("First Line:",line1)
line2=file.readline()
print(line2)
line3=file.readline()
print(line3)
file.close()

First Line: Hello, B.tech students|

This is file handling in python.

sr universitysuresh kumar


In [12]:
#6.Reading All lines into a list
file=open("example.txt","r")
lines=file.readlines()
print(lines)
file.close()

['Hello, B.tech students|\n', 'This is file handling in python.\n', 'sr universitysuresh kumar']


In [14]:
#7.Appending data to an existing file
file=open("example.txt","a")
file.write("Appending new data...\n")
file.close()

In [8]:
with open("example.txt","r")as file:
    content=file.read()
    print(content)

Hello, B.tech students|
This is file handling in python.
sr universitysuresh kumar


In [16]:
import csv
#writing to csv
with open("data.csv", "w", newline='')as fp:
  wr=csv.writer(fp)
  wr.writerows([["Name", "Age", "course"],["aaa",21,"CSE"],["bbb", 20, "ECE"]])


In [17]:
#Reading from csv
with open("data.csv","r")as fp:
  rd=csv.reader(fp)
  for row in rd:
    print(row)

['Name', 'Age', 'course']
['aaa', '21', 'CSE']
['bbb', '20', 'ECE']


In [20]:
#1DArray
import numpy as np
arr1=np.array([1,2,3,4])
print("1D Array:",arr1)

1D Array: [1 2 3 4]


In [21]:
#2D array
arr2=np.array([[1,2,3],[4,5,6]])
print("2D Array:")
print(arr2)

2D Array:
[[1 2 3]
 [4 5 6]]


In [22]:
#Zeros Array
zeros_arr=np.zeros((3,3))
print("Zeros Array:")
print(zeros_arr)

Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
#ones Array
ones_arr=np.ones((2,4))
print("Ones Array:")
print(ones_arr)

Ones Array:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [24]:
#Range of numbers
range_arr=np.arange(0,10,2)
print("Range Array:")
print(range_arr)

Range Array:
[0 2 4 6 8]


In [25]:
#Random array
rand_arr=np.random.rand(2,3)
print("Random Array:")
print(rand_arr)

Random Array:
[[0.59530315 0.91426241 0.88691059]
 [0.5876366  0.37176954 0.55261689]]


In [26]:
#Array Attributes
arr=np.array([[1,2,3],[4,5,6]])
print("Shape:",arr.shape)
print("Dimension:",arr.ndim)
print("Size:",arr.size)
print("Data Type:",arr.dtype)
print("Item Size:",arr.itemsize)
print("Type:",type(arr))

Shape: (2, 3)
Dimension: 2
Size: 6
Data Type: int64
Item Size: 8
Type: <class 'numpy.ndarray'>


In [27]:
#Array indexing and slicing
arr=np.array([10,20,30,40,50])
print("First element:",arr[0])
print("Slice[1:4]:",arr[1:4])
print("Every second element:",arr[::2])

First element: 10
Slice[1:4]: [20 30 40]
Every second element: [10 30 50]


In [28]:
#2D indexing
arr2=np.array([[1,2,3],[4,5,6]])
print("Element at row 1,col 2:",arr2[0,1])
print("Second row:",arr2[1,:])
print("Second column:",arr2[:, 1])

Element at row 1,col 2: 2
Second row: [4 5 6]
Second column: [2 5]


In [36]:
#Array operations
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Addition:",a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("power:",a**2)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
power: [1 4 9]


In [31]:
arr = np.array([0, np.pi/2, np.pi])
print("Sine:", np.sin(arr))
print("Cosine:", np.cos(arr))
print("Square root:", np.sqrt([1, 4, 9]))
print("Exponential:", np.exp([1, 2]))
print("Logarithm:", np.log([1, np.e, np.e**2]))

Sine: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cosine: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Square root: [1. 2. 3.]
Exponential: [2.71828183 7.3890561 ]
Logarithm: [0. 1. 2.]


In [33]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Sum:", np.sum(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))
print("Sum along axis 0:", np.sum(arr, axis=0))
print("Sum along axis 1:", np.sum(arr,axis=1))

Sum: 21
Max: 6
Min: 1
Mean: 3.5
Standard Deviation: 1.707825127659933
Sum along axis 0: [5 7 9]
Sum along axis 1: [ 6 15]


In [35]:
a = np.array([1, 2, 3])
b = 5
print("Add scalar to array:", a + b)  # [6 7 8]

c = np.array([[1], [2], [3]])
d = np.array([4, 5, 6])
print("Broadcasted sum:\n",c+d)

Add scalar to array: [6 7 8]
Broadcasted sum:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [37]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix Multiplication:\n", np.dot(A, B))
print("Transpose:\n", A.T)
print("Inverse:\n", np.linalg.inv(A))
print("Determinant:", np.linalg.det(A))

Matrix Multiplication:
 [[19 22]
 [43 50]]
Transpose:
 [[1 3]
 [2 4]]
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant: -2.0000000000000004


In [39]:
import numpy as np

# Marks of students in 3 subjects
marks = np.array([
    [85, 90, 88],
    [78, 81, 85],
    [92, 89, 95]
])

print("Average marks per student:", np.mean(marks, axis=1))
print("Average marks per subject:", np.mean(marks, axis=0))
print("Highest marks in each subject:", np.max(marks, axis=0))
print("Lowest marks in each subject:", np.min(marks,axis=0))

Average marks per student: [87.66666667 81.33333333 92.        ]
Average marks per subject: [85.         86.66666667 89.33333333]
Highest marks in each subject: [92 90 95]
Lowest marks in each subject: [78 81 85]
